-- Debug --
---- Afficher les tableaux ----
SELECT * from OUTILS_OUTIL;
SELECT * from OUTILS_EMPRUNT;
SELECT * from OUTILS_USAGER;

-- Question 1 --
DESCRIBE OUTILS_OUTIL;
DESCRIBE OUTILS_EMPRUNT;
DESCRIBE OUTILS_USAGER;

-- Question 2 --
SELECT CONCAT(PRENOM, ' ', NOM_FAMILLE) AS "Nom Complet" FROM OUTILS_USAGER;

-- Question 3 --
SELECT DISTINCT VILLE FROM OUTILS_USAGER ORDER BY VILLE ASC;

-- Question 4 --
SELECT * FROM OUTILS_OUTIL ORDER BY NOM ASC, CODE_OUTIL ASC;

-- Question 5 --
SELECT NUM_EMPRUNT FROM OUTILS_EMPRUNT WHERE DATE_RETOUR IS NULL;

-- Question 6 --
SELECT NUM_EMPRUNT FROM OUTILS_EMPRUNT WHERE EXTRACT(YEAR FROM DATE_EMPRUNT) < 2014;

-- Question 7 --
SELECT NOM, CODE_OUTIL FROM OUTILS_OUTIL WHERE UPPER(CARACTERISTIQUES) LIKE '%J%';

-- Question 8 --
SELECT NOM, CODE_OUTIL FROM OUTILS_OUTIL WHERE FABRICANT = 'Stanley';

-- Question 9 --
SELECT NOM, FABRICANT FROM OUTILS_OUTIL WHERE ANNEE BETWEEN 2006 AND 2008;

-- Question 10 --
SELECT CODE_OUTIL, NOM FROM OUTILS_OUTIL WHERE CARACTERISTIQUES NOT LIKE '%20 volt%';

-- Question 11 --
SELECT COUNT(*) FROM OUTILS_OUTIL WHERE FABRICANT <> 'Makita';

-- Question 12 --
SELECT CONCAT(U.PRENOM, ' ', U.NOM_FAMILLE) AS "Nom Complet",
       E.NUM_EMPRUNT,
       NVL(E.DATE_RETOUR, SYSDATE) - E.DATE_EMPRUNT AS "Durée de l'emprunt",
       NVL(O.PRIX, 0) AS "Prix de l'outil"
FROM OUTILS_EMPRUNT E
         JOIN OUTILS_USAGER U ON E.NUM_USAGER = U.NUM_USAGER
         JOIN OUTILS_OUTIL O ON E.CODE_OUTIL = O.CODE_OUTIL
WHERE U.VILLE IN ('Vancouver', 'Regina');

-- Question 13 --
SELECT O.NOM, O.CODE_OUTIL
FROM OUTILS_OUTIL O
         JOIN OUTILS_EMPRUNT E ON O.CODE_OUTIL = E.CODE_OUTIL
WHERE E.DATE_RETOUR IS NULL;

-- Question 14 --
SELECT CONCAT(PRENOM, ' ', NOM_FAMILLE) AS "Nom Complet", COURRIEL
FROM OUTILS_USAGER
WHERE NUM_USAGER NOT IN (SELECT NUM_USAGER FROM OUTILS_EMPRUNT);

-- Question 15 --
SELECT O.CODE_OUTIL, O.PRIX AS "Valeur"
FROM OUTILS_OUTIL O
         LEFT OUTER JOIN OUTILS_EMPRUNT E ON O.CODE_OUTIL = E.CODE_OUTIL
WHERE E.NUM_EMPRUNT IS NULL;

-- Question 16 --
SELECT NOM, NVL(PRIX, (SELECT AVG(PRIX) FROM OUTILS_OUTIL WHERE PRIX IS NOT NULL)) AS "Prix"
FROM OUTILS_OUTIL
WHERE FABRICANT = 'Makita' AND PRIX > (SELECT AVG(PRIX) FROM OUTILS_OUTIL WHERE PRIX IS NOT NULL);

-- Question 17 --
SELECT U.NOM_FAMILLE, U.PRENOM, U.ADRESSE, O.NOM, O.CODE_OUTIL
FROM OUTILS_EMPRUNT E
         JOIN OUTILS_USAGER U ON E.NUM_USAGER = U.NUM_USAGER
         JOIN OUTILS_OUTIL O ON E.CODE_OUTIL = O.CODE_OUTIL
WHERE EXTRACT(YEAR FROM E.DATE_EMPRUNT) > 2014
ORDER BY U.NOM_FAMILLE;

-- Question 18 --
SELECT O.NOM, O.PRIX
FROM OUTILS_OUTIL O
         JOIN OUTILS_EMPRUNT E ON O.CODE_OUTIL = E.CODE_OUTIL
GROUP BY O.NOM, O.PRIX
HAVING COUNT(E.NUM_EMPRUNT) > 1;

-- Question 19 --
---- AVEC JOINTURE ----
SELECT U.NOM_FAMILLE, U.ADRESSE, U.VILLE
FROM OUTILS_USAGER U
         JOIN OUTILS_EMPRUNT E ON U.NUM_USAGER = E.NUM_USAGER;

---- AVEC IN ----
SELECT NOM_FAMILLE, ADRESSE, VILLE
FROM OUTILS_USAGER
WHERE NUM_USAGER IN (SELECT NUM_USAGER FROM OUTILS_EMPRUNT);

---- AVEC EXISTS ----
SELECT NOM_FAMILLE, ADRESSE, VILLE
FROM OUTILS_USAGER U
WHERE EXISTS (SELECT 1 FROM OUTILS_EMPRUNT E WHERE U.NUM_USAGER = E.NUM_USAGER);

-- Question 20 --
SELECT FABRICANT, AVG(PRIX) AS "Average Price"
FROM OUTILS_OUTIL
GROUP BY FABRICANT;

-- Question 21 --
SELECT U.VILLE, SUM(O.PRIX) AS "Total Price"
FROM OUTILS_EMPRUNT E
         JOIN OUTILS_USAGER U ON E.NUM_USAGER = U.NUM_USAGER
         JOIN OUTILS_OUTIL O ON E.CODE_OUTIL = O.CODE_OUTIL
GROUP BY U.VILLE
ORDER BY "Total Price" DESC;

-- Question 22 --
INSERT INTO OUTILS_OUTIL (CODE_OUTIL, NOM, FABRICANT, CARACTERISTIQUES, ANNEE, PRIX)
VALUES ('TO789', 'Marteau-Piqueur', 'BAT', '30 volt, jaune', 2022, 800);

-- Question 23 --
INSERT INTO OUTILS_OUTIL (CODE_OUTIL, NOM, ANNEE)
    VALUES ('TO790', 'Gros marteau', 2012);

-- Question 24 --
DELETE FROM OUTILS_OUTIL WHERE CODE_OUTIL IN ('TO789', 'TO790');

-- Question 25 --
UPDATE OUTILS_USAGER
SET NOM_FAMILLE = UPPER(NOM_FAMILLE);
